id: I5FC3178F
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:07:25.090316
last_modified: 2023-02-09 15:07:25.090425
source_metadata:
  title: 'MSV 1,08: Kaṭhinavastu'
  language: bo
bases:
  9DC4:
    base_file: 9DC4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
